name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          submodules: true
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3.3.1
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          commit-ish: HEAD
      - name: Check pre-release
        run: |
          echo "tag=${{steps.tagger.outputs.tag}}"
          if [[ ${{ steps.tagger.outputs.tag }} == *alpha* || ${{ steps.tagger.outputs.tag }} == *beta* ]]
          then
             prerelease=true
          else
             prerelease=false
          fi
          echo "PRE_RELEASE=$prerelease" >> $GITHUB_ENV
          echo "prerelease=$prerelease"
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.3
      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Build project
        run: ./gradlew assembleRelease
        env:
          TAG_VERSION: ${{ github.ref }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.tagger.outputs.tag}}
          generate_release_notes: true
          prerelease: ${{ env.PRE_RELEASE }}
          name: ${{steps.tagger.outputs.tag}}
          files: |
            ./owncloudApp/build/outputs/apk/original/release/owncloud_2.21.1.0-original-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          assetsAPK=$(find . -name *.apk | while read -r asset ; do echo "-a $asset" ; done)
          hub release create ${assetsAPK} -m "${{steps.tagger.outputs.tag}}" "${{steps.tagger.outputs.tag}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}

      - name: cleanup keystore
        run: ./signing/cleanup.sh